export const cardStyles = {
  base: {
    background: 'var(--white)',
    border: '1px solid var(--border)',
    borderRadius: 14,
    padding: '20px 20px 18px',
    boxShadow: '0 1px 2px rgba(60, 50, 30, 0.04)',
    cursor: 'pointer',
    transition: 'all 240ms var(--ease)',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  meta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: 12.5,
    color: 'var(--muted)',
    fontWeight: 500,
  },
  duration: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    fontSize: 11.5,
    color: 'var(--muted)',
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 450,
  },
  preview: {
    fontSize: 13.5,
    color: 'var(--dark-soft)',
    lineHeight: 1.55,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    fontFamily: "'Lora', Georgia, serif",
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    fontSize: 10.5,
    fontWeight: 600,
    padding: '3px 9px',
    borderRadius: 999,
    letterSpacing: '0.03em',
    fontFamily: 'var(--sans)',
    textTransform: 'uppercase',
  },
};
